### ISSUE TITLE
Getting Committees from within python

### ISSUE THREAD

**Issue by WJLiddy** [nanflasted/C-SPAN#4]
I can use 
dbc = dbmngr.connectDB("./data/","cspdb",False)
idcur = dbmngr.queryEntry(dbc,["id"],["legislators"])
idlist = idcur.fetchall()

To get all the IDs of the Legislators. However,

commcur = dbmngr.queryEntry(dbc,["id"],["committees"])
commlist = idcur.fetchall()

Gives me an empty list for the committee ids. What am I doing wrong?

**Comment by WJLiddy** [comment]
See
https://github.com/nanflasted/C-SPAN/blob/master/frontend/generate_content_forever.py

**Comment by nanflasted** [comment]
commcur = dbmngr.queryEntry(dbc,["id"],["committees"])
commlist = _**idcur**_.fetchall()
mfw

**Comment by nanflasted** [comment]
Also wouldn't it go too fast? if you comment out the time.sleep()?

**Comment by WJLiddy** [comment]
Sorry I'm a bad coder

**Comment by WJLiddy** [comment]
To be fair it was 3 am tho
